// GL_VERSION_1_2
GL_FUNCTION(glDrawRangeElements ,void, (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices))
GL_FUNCTION(glTexImage3D, void, (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels))
GL_FUNCTION(glTexSubImage3D, void, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels))
GL_FUNCTION(glCopyTexSubImage3D, void, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height))

// GL_VERSION_1_3
GL_FUNCTION(glActiveTexture,void,(GLenum texture))
GL_FUNCTION(glClientActiveTexture,void,(GLenum texture))
GL_FUNCTION(glCompressedTexImage1D,void,(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data))
GL_FUNCTION(glCompressedTexImage2D,void,(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data))
GL_FUNCTION(glCompressedTexImage3D,void,(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data))
GL_FUNCTION(glCompressedTexSubImage1D,void,(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data))
GL_FUNCTION(glCompressedTexSubImage2D,void,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data))
GL_FUNCTION(glCompressedTexSubImage3D,void,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data))
GL_FUNCTION(glGetCompressedTexImage,void,(GLenum target, GLint lod, GLvoid *img))
GL_FUNCTION(glLoadTransposeMatrixd,void,(const GLdouble m[16]))
GL_FUNCTION(glLoadTransposeMatrixf,void,(const GLfloat m[16]))
GL_FUNCTION(glMultTransposeMatrixd,void,(const GLdouble m[16]))
GL_FUNCTION(glMultTransposeMatrixf,void,(const GLfloat m[16]))
GL_FUNCTION(glMultiTexCoord1d,void,(GLenum target, GLdouble s))
GL_FUNCTION(glMultiTexCoord1dv,void,(GLenum target, const GLdouble *v))
GL_FUNCTION(glMultiTexCoord1f,void,(GLenum target, GLfloat s))
GL_FUNCTION(glMultiTexCoord1fv,void,(GLenum target, const GLfloat *v))
GL_FUNCTION(glMultiTexCoord1i,void,(GLenum target, GLint s))
GL_FUNCTION(glMultiTexCoord1iv,void,(GLenum target, const GLint *v))
GL_FUNCTION(glMultiTexCoord1s,void,(GLenum target, GLshort s))
GL_FUNCTION(glMultiTexCoord1sv,void,(GLenum target, const GLshort *v))
GL_FUNCTION(glMultiTexCoord2d,void,(GLenum target, GLdouble s, GLdouble t))
GL_FUNCTION(glMultiTexCoord2dv,void,(GLenum target, const GLdouble *v))
GL_FUNCTION(glMultiTexCoord2f,void,(GLenum target, GLfloat s, GLfloat t))
GL_FUNCTION(glMultiTexCoord2fv,void,(GLenum target, const GLfloat *v))
GL_FUNCTION(glMultiTexCoord2i,void,(GLenum target, GLint s, GLint t))
GL_FUNCTION(glMultiTexCoord2iv,void,(GLenum target, const GLint *v))
GL_FUNCTION(glMultiTexCoord2s,void,(GLenum target, GLshort s, GLshort t))
GL_FUNCTION(glMultiTexCoord2sv,void,(GLenum target, const GLshort *v))
GL_FUNCTION(glMultiTexCoord3d,void,(GLenum target, GLdouble s, GLdouble t, GLdouble r))
GL_FUNCTION(glMultiTexCoord3dv,void,(GLenum target, const GLdouble *v))
GL_FUNCTION(glMultiTexCoord3f,void,(GLenum target, GLfloat s, GLfloat t, GLfloat r))
GL_FUNCTION(glMultiTexCoord3fv,void,(GLenum target, const GLfloat *v))
GL_FUNCTION(glMultiTexCoord3i,void,(GLenum target, GLint s, GLint t, GLint r))
GL_FUNCTION(glMultiTexCoord3iv,void,(GLenum target, const GLint *v))
GL_FUNCTION(glMultiTexCoord3s,void,(GLenum target, GLshort s, GLshort t, GLshort r))
GL_FUNCTION(glMultiTexCoord3sv,void,(GLenum target, const GLshort *v))
GL_FUNCTION(glMultiTexCoord4d,void,(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q))
GL_FUNCTION(glMultiTexCoord4dv,void,(GLenum target, const GLdouble *v))
GL_FUNCTION(glMultiTexCoord4f,void,(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q))
GL_FUNCTION(glMultiTexCoord4fv,void,(GLenum target, const GLfloat *v))
GL_FUNCTION(glMultiTexCoord4i,void,(GLenum target, GLint s, GLint t, GLint r, GLint q))
GL_FUNCTION(glMultiTexCoord4iv,void,(GLenum target, const GLint *v))
GL_FUNCTION(glMultiTexCoord4s,void,(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q))
GL_FUNCTION(glMultiTexCoord4sv,void,(GLenum target, const GLshort *v))
GL_FUNCTION(glSampleCoverage,void,(GLclampf value, GLboolean invert))

// GL_VERSION_1_4
GL_FUNCTION(glBlendEquation,void,(GLenum mode))
GL_FUNCTION(glBlendColor,void,(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha))
GL_FUNCTION(glFogCoordf,void,(GLfloat coord))
GL_FUNCTION(glFogCoordfv,void,(const GLfloat *coord))
GL_FUNCTION(glFogCoordd,void,(GLdouble coord))
GL_FUNCTION(glFogCoorddv,void,(const GLdouble *coord))
GL_FUNCTION(glFogCoordPointer,void,(GLenum type, GLsizei stride, const GLvoid *pointer))
GL_FUNCTION(glMultiDrawArrays,void,(GLenum mode, GLint *first, GLsizei *count, GLsizei primcount))
GL_FUNCTION(glMultiDrawElements,void,(GLenum mode, GLsizei *count, GLenum type, const GLvoid **indices, GLsizei primcount))
GL_FUNCTION(glPointParameterf,void,(GLenum pname, GLfloat param))
GL_FUNCTION(glPointParameterfv,void,(GLenum pname, GLfloat *params))
GL_FUNCTION(glSecondaryColor3b,void,(GLbyte red, GLbyte green, GLbyte blue))
GL_FUNCTION(glSecondaryColor3bv,void,(const GLbyte *v))
GL_FUNCTION(glSecondaryColor3d,void,(GLdouble red, GLdouble green, GLdouble blue))
GL_FUNCTION(glSecondaryColor3dv,void,(const GLdouble *v))
GL_FUNCTION(glSecondaryColor3f,void,(GLfloat red, GLfloat green, GLfloat blue))
GL_FUNCTION(glSecondaryColor3fv,void,(const GLfloat *v))
GL_FUNCTION(glSecondaryColor3i,void,(GLint red, GLint green, GLint blue))
GL_FUNCTION(glSecondaryColor3iv,void,(const GLint *v))
GL_FUNCTION(glSecondaryColor3s,void,(GLshort red, GLshort green, GLshort blue))
GL_FUNCTION(glSecondaryColor3sv,void,(const GLshort *v))
GL_FUNCTION(glSecondaryColor3ub,void,(GLubyte red, GLubyte green, GLubyte blue))
GL_FUNCTION(glSecondaryColor3ubv,void,(const GLubyte *v))
GL_FUNCTION(glSecondaryColor3ui,void,(GLuint red, GLuint green, GLuint blue))
GL_FUNCTION(glSecondaryColor3uiv,void,(const GLuint *v))
GL_FUNCTION(glSecondaryColor3us,void,(GLushort red, GLushort green, GLushort blue))
GL_FUNCTION(glSecondaryColor3usv,void,(const GLushort *v))
GL_FUNCTION(glSecondaryColorPointer,void,(GLint size, GLenum type, GLsizei stride, GLvoid *pointer))
GL_FUNCTION(glBlendFuncSeparate,void,(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha))
GL_FUNCTION(glWindowPos2d,void,(GLdouble x, GLdouble y))
GL_FUNCTION(glWindowPos2f,void,(GLfloat x, GLfloat y))
GL_FUNCTION(glWindowPos2i,void,(GLint x, GLint y))
GL_FUNCTION(glWindowPos2s,void,(GLshort x, GLshort y))
GL_FUNCTION(glWindowPos2dv,void,(const GLdouble *p))
GL_FUNCTION(glWindowPos2fv,void,(const GLfloat *p))
GL_FUNCTION(glWindowPos2iv,void,(const GLint *p))
GL_FUNCTION(glWindowPos2sv,void,(const GLshort *p))
GL_FUNCTION(glWindowPos3d,void,(GLdouble x, GLdouble y, GLdouble z))
GL_FUNCTION(glWindowPos3f,void,(GLfloat x, GLfloat y, GLfloat z))
GL_FUNCTION(glWindowPos3i,void,(GLint x, GLint y, GLint z))
GL_FUNCTION(glWindowPos3s,void,(GLshort x, GLshort y, GLshort z))
GL_FUNCTION(glWindowPos3dv,void,(const GLdouble *p))
GL_FUNCTION(glWindowPos3fv,void,(const GLfloat *p))
GL_FUNCTION(glWindowPos3iv,void,(const GLint *p))
GL_FUNCTION(glWindowPos3sv,void,(const GLshort *p))

// GL_VERSION_1_5
GL_FUNCTION(glGenQueries,void,(GLsizei n, GLuint* ids))
GL_FUNCTION(glDeleteQueries,void,(GLsizei n, const GLuint* ids))
GL_FUNCTION(glIsQuery,GLboolean,(GLuint id))
GL_FUNCTION(glBeginQuery,void,(GLenum target, GLuint id))
GL_FUNCTION(glEndQuery,void,(GLenum target))
GL_FUNCTION(glGetQueryiv,void,(GLenum target, GLenum pname, GLint* params))
GL_FUNCTION(glGetQueryObjectiv,void,(GLuint id, GLenum pname, GLint* params))
GL_FUNCTION(glGetQueryObjectuiv,void,(GLuint id, GLenum pname, GLuint* params))
GL_FUNCTION(glBindBuffer,void,(GLenum target, GLuint buffer))
GL_FUNCTION(glDeleteBuffers,void,(GLsizei n, const GLuint* buffers))
GL_FUNCTION(glGenBuffers,void,(GLsizei n, GLuint* buffers))
GL_FUNCTION(glIsBuffer,GLboolean,(GLuint buffer))
GL_FUNCTION(glBufferData,void,(GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage))
GL_FUNCTION(glBufferSubData,void,(GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data))
GL_FUNCTION(glGetBufferSubData,void,(GLenum target, GLintptr offset, GLsizeiptr size, GLvoid* data))
GL_FUNCTION(glMapBuffer,GLvoid*,(GLenum target, GLenum access))
GL_FUNCTION(glUnmapBuffer,GLboolean,(GLenum target))
GL_FUNCTION(glGetBufferParameteriv,void,(GLenum target, GLenum pname, GLint* params))
GL_FUNCTION(glGetBufferPointerv,void,(GLenum target, GLenum pname, GLvoid** params))

// GL_VERSION_2_0
GL_FUNCTION(glBlendEquationSeparate,void,(GLenum, GLenum))
GL_FUNCTION(glDrawBuffers,void,(GLsizei n, const GLenum* bufs))
GL_FUNCTION(glStencilOpSeparate,void,(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass))
GL_FUNCTION(glStencilFuncSeparate,void,(GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask))
GL_FUNCTION(glStencilMaskSeparate,void,(GLenum, GLuint))
GL_FUNCTION(glAttachShader,void,(GLuint program, GLuint shader))
GL_FUNCTION(glBindAttribLocation,void,(GLuint program, GLuint index, const GLchar* name))
GL_FUNCTION(glCompileShader,void,(GLuint shader))
GL_FUNCTION(glCreateProgram,GLuint,(void))
GL_FUNCTION(glCreateShader,GLuint,(GLenum type))
GL_FUNCTION(glDeleteProgram,void,(GLuint program))
GL_FUNCTION(glDeleteShader,void,(GLuint shader))
GL_FUNCTION(glDetachShader,void,(GLuint program, GLuint shader))
GL_FUNCTION(glDisableVertexAttribArray,void,(GLuint))
GL_FUNCTION(glEnableVertexAttribArray,void,(GLuint))
GL_FUNCTION(glGetActiveAttrib,void,(GLuint program, GLuint index, GLsizei maxLength, GLsizei* length, GLint* size, GLenum* type, GLchar* name))
GL_FUNCTION(glGetActiveUniform,void,(GLuint program, GLuint index, GLsizei maxLength, GLsizei* length, GLint* size, GLenum* type, GLchar* name))
GL_FUNCTION(glGetAttachedShaders,void,(GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders))
GL_FUNCTION(glGetAttribLocation,GLint,(GLuint program, const GLchar* name))
GL_FUNCTION(glGetProgramiv,void,(GLuint program, GLenum pname, GLint* param))
GL_FUNCTION(glGetProgramInfoLog,void,(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog))
GL_FUNCTION(glGetShaderiv,void,(GLuint shader, GLenum pname, GLint* param))
GL_FUNCTION(glGetShaderInfoLog,void,(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog))
GL_FUNCTION(glShaderSource,void,(GLuint shader, GLsizei count, const GLchar** strings, const GLint* lengths))
GL_FUNCTION(glGetUniformLocation,GLint,(GLint programObj, const GLchar* name))
GL_FUNCTION(glGetUniformfv,void,(GLuint program, GLint location, GLfloat* params))
GL_FUNCTION(glGetUniformiv,void,(GLuint program, GLint location, GLint* params))
GL_FUNCTION(glGetVertexAttribdv,void,(GLuint, GLenum, GLdouble*))
GL_FUNCTION(glGetVertexAttribfv,void,(GLuint, GLenum, GLfloat*))
GL_FUNCTION(glGetVertexAttribiv,void,(GLuint, GLenum, GLint*))
GL_FUNCTION(glGetVertexAttribPointerv,void,(GLuint, GLenum, GLvoid*))
GL_FUNCTION(glIsProgram,GLboolean,(GLuint program))
GL_FUNCTION(glIsShader,GLboolean,(GLuint shader))
GL_FUNCTION(glLinkProgram,void,(GLuint program))
GL_FUNCTION(glGetShaderSource,void,(GLint obj, GLsizei maxLength, GLsizei* length, GLchar* source))
GL_FUNCTION(glUseProgram,void,(GLuint program))
GL_FUNCTION(glUniform1f,void,(GLint location, GLfloat v0))
GL_FUNCTION(glUniform1fv,void,(GLint location, GLsizei count, const GLfloat* value))
GL_FUNCTION(glUniform1i,void,(GLint location, GLint v0))
GL_FUNCTION(glUniform1iv,void,(GLint location, GLsizei count, const GLint* value))
GL_FUNCTION(glUniform2f,void,(GLint location, GLfloat v0, GLfloat v1))
GL_FUNCTION(glUniform2fv,void,(GLint location, GLsizei count, const GLfloat* value))
GL_FUNCTION(glUniform2i,void,(GLint location, GLint v0, GLint v1))
GL_FUNCTION(glUniform2iv,void,(GLint location, GLsizei count, const GLint* value))
GL_FUNCTION(glUniform3f,void,(GLint location, GLfloat v0, GLfloat v1, GLfloat v2))
GL_FUNCTION(glUniform3fv,void,(GLint location, GLsizei count, const GLfloat* value))
GL_FUNCTION(glUniform3i,void,(GLint location, GLint v0, GLint v1, GLint v2))
GL_FUNCTION(glUniform3iv,void,(GLint location, GLsizei count, const GLint* value))
GL_FUNCTION(glUniform4f,void,(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3))
GL_FUNCTION(glUniform4fv,void,(GLint location, GLsizei count, const GLfloat* value))
GL_FUNCTION(glUniform4i,void,(GLint location, GLint v0, GLint v1, GLint v2, GLint v3))
GL_FUNCTION(glUniform4iv,void,(GLint location, GLsizei count, const GLint* value))
GL_FUNCTION(glUniformMatrix2fv,void,(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value))
GL_FUNCTION(glUniformMatrix3fv,void,(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value))
GL_FUNCTION(glUniformMatrix4fv,void,(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value))
GL_FUNCTION(glValidateProgram,void,(GLuint program))
GL_FUNCTION(glVertexAttrib1d,void,(GLuint index, GLdouble x))
GL_FUNCTION(glVertexAttrib1dv,void,(GLuint index, const GLdouble* v))
GL_FUNCTION(glVertexAttrib1f,void,(GLuint index, GLfloat x))
GL_FUNCTION(glVertexAttrib1fv,void,(GLuint index, const GLfloat* v))
GL_FUNCTION(glVertexAttrib1s,void,(GLuint index, GLshort x))
GL_FUNCTION(glVertexAttrib1sv,void,(GLuint index, const GLshort* v))
GL_FUNCTION(glVertexAttrib2d,void,(GLuint index, GLdouble x, GLdouble y))
GL_FUNCTION(glVertexAttrib2dv,void,(GLuint index, const GLdouble* v))
GL_FUNCTION(glVertexAttrib2f,void,(GLuint index, GLfloat x, GLfloat y))
GL_FUNCTION(glVertexAttrib2fv,void,(GLuint index, const GLfloat* v))
GL_FUNCTION(glVertexAttrib2s,void,(GLuint index, GLshort x, GLshort y))
GL_FUNCTION(glVertexAttrib2sv,void,(GLuint index, const GLshort* v))
GL_FUNCTION(glVertexAttrib3d,void,(GLuint index, GLdouble x, GLdouble y, GLdouble z))
GL_FUNCTION(glVertexAttrib3dv,void,(GLuint index, const GLdouble* v))
GL_FUNCTION(glVertexAttrib3f,void,(GLuint index, GLfloat x, GLfloat y, GLfloat z))
GL_FUNCTION(glVertexAttrib3fv,void,(GLuint index, const GLfloat* v))
GL_FUNCTION(glVertexAttrib3s,void,(GLuint index, GLshort x, GLshort y, GLshort z))
GL_FUNCTION(glVertexAttrib3sv,void,(GLuint index, const GLshort* v))
GL_FUNCTION(glVertexAttrib4Nbv,void,(GLuint index, const GLbyte* v))
GL_FUNCTION(glVertexAttrib4Niv,void,(GLuint index, const GLint* v))
GL_FUNCTION(glVertexAttrib4Nsv,void,(GLuint index, const GLshort* v))
GL_FUNCTION(glVertexAttrib4Nub,void,(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w))
GL_FUNCTION(glVertexAttrib4Nubv,void,(GLuint index, const GLubyte* v))
GL_FUNCTION(glVertexAttrib4Nuiv,void,(GLuint index, const GLuint* v))
GL_FUNCTION(glVertexAttrib4Nusv,void,(GLuint index, const GLushort* v))
GL_FUNCTION(glVertexAttrib4bv,void,(GLuint index, const GLbyte* v))
GL_FUNCTION(glVertexAttrib4d,void,(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w))
GL_FUNCTION(glVertexAttrib4dv,void,(GLuint index, const GLdouble* v))
GL_FUNCTION(glVertexAttrib4f,void,(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
GL_FUNCTION(glVertexAttrib4fv,void,(GLuint index, const GLfloat* v))
GL_FUNCTION(glVertexAttrib4iv,void,(GLuint index, const GLint* v))
GL_FUNCTION(glVertexAttrib4s,void,(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w))
GL_FUNCTION(glVertexAttrib4sv,void,(GLuint index, const GLshort* v))
GL_FUNCTION(glVertexAttrib4ubv,void,(GLuint index, const GLubyte* v))
GL_FUNCTION(glVertexAttrib4uiv,void,(GLuint index, const GLuint* v))
GL_FUNCTION(glVertexAttrib4usv,void,(GLuint index, const GLushort* v))
GL_FUNCTION(glVertexAttribPointer,void,(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid* pointer))


